Repository FECrash/Programming-TypeScript, pull requests merged in 2022-08, with the labels that each got.

#8 05. 클래스와 인터페이스
  05-클래스와_인터페이스/Class_Interface.md
Labels: 5장

#10 [프로그래밍 타입스크립트] 6장 정리
  06-고급_타입/06-고급_타입.md
Labels: 6장

#14 구글 설문지로 퀴즈를 진행한다.
  00-쪽지시험/README.md
Labels: QUIZ

#15 [프로그래밍 타입스크립트] 7장 정리
  01-소개/01-소개.md
  02-타입스크립트_300미터_상공에서_내려다보기/02-타입스크립트_300미터_상공에서_내려다보기.md
  07-에러_처리/07-에러_처리.md
Labels: 7장
